# Generated by Django 5.0.2 on 2024-03-22 22:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_person_remove_user_age_remove_user_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('id_dept', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 163085))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 163085))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 162522))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 162522))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('id_country', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 163085))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 163085))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identification_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=10)),
                ('descrip', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 163085))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 163085))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('id_person', models.IntegerField()),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 161458))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 161458))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_at',
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 160873)),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.user'),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 160873)),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 61758)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 17, 14, 19, 61758)),
        ),
    ]
